{{- if not .Values.veeam.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "veeam-exporter.secretName" . }}
  labels:
    {{- include "veeam-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.veeam.auth.usernameKey }}: {{ .Values.veeam.auth.username | quote }}
  {{ .Values.veeam.auth.passwordKey }}: {{ .Values.veeam.auth.password | quote }}
{{- end }}
